//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int Id { get; set; }
        public string NamePet { get; set; }
        public string Sex { get; set; }
        public string Species { get; set; }
        public string Breed { get; set; }
        public int Age { get; set; }
        public int Weigth { get; set; }
        public int OwnersId { get; set; }
    
        internal virtual Owners Owners { get; set; }
    }
}
