//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets_And_Owners
    {
        public string Порода { get; set; }
        public string Пол { get; set; }
        public string Имя_питомца { get; set; }
        public string Имя { get; set; }
        public string Телефон { get; set; }
        public int Id { get; set; }
        public int OwnersId { get; set; }
    }
}
